name: Build and deploy fastapi

on: [push, pull_request]

jobs:
    job1: 
        runs-on: ubuntu-latest
        steps:
            - name: pull repo
              uses: actions/checkout@v2
            - name: say hai to madhu
              run: echo "Hello madhu"

